### ISSUE TITLE
Requests don't work in the swagger docs

### ISSUE THREAD

**Issue by kennib** [kennib/Boomerang#10]
When using the "try it out" [docs](https://store.ncss.cloud/docs/) the request is made, but the supplied JSON is never sent with the request.

**Comment by kennib** [comment]
[Swagger UI]( https://swagger.io/tools/swagger-ui/) is the tool used for the docs.

**Comment by joelgibson** [comment]
Fixed by d868aeb706e658e64b69351f4ebee8b5569efdc2
