### ISSUE TITLE
DELETE /key should probably return 404

### ISSUE THREAD

**Issue by cyphar** [kennib/Boomerang#8]
If a key does not exist, `DELETE /key` will still return `204`. While this isn't necessarily _bad_, we probably should return a `404` if the key is not known. The main issue is that there is no obvious way to return an error from `DELETE FROM` if the key is not present. You can do a `SELECT count(*)` check before-hand but that just opens you to race conditions.

**Comment by kennib** [comment]
I'm not sure what negative effects you could get from a `DELETE` race condition that aren't also inherent in the async nature of HTTP APIs. You can and should `BEGIN TRANSACTION; ... COMMIT;` around the `SELECT` and `DELETE FROM` SQL statements, but I think it barely buys us any extra guarantee that the key hasn't been added again while the response was being sent back to the API user.

**Comment by cyphar** [comment]
My point was if you did a `DELETE` of a non-existent key, arguably you should get a `404`. But I'll admit this isn't really a huge problem -- I imagine most students won't care if a key actually existed when they decided to delete it (most likely this would be used for cleanup routines anyway).

**Comment by cyphar** [comment]
I'll mention in the docs that even if the key doesn't exist you get a 204.
