### ISSUE TITLE
GET /key: 'Value' model is not accurate

### ISSUE THREAD

**Issue by cyphar** [kennib/Boomerang#9]
The model claims that `GET /key` will return a `Value` JSON blob like:

```
{
  "key": "group1/users/georgina",
  "value": {
    "food": "marzipan",
    "name": "georgina"
  }
}
```

But in fact, it will return blobs like:

```
{
    "food": "marzipan",
    "name": "georgina"
}
```

This is totally fine for an API but we need to update the documentation to avoid student confusion (some students might start inserting keys using the provided model, while others use the API "correctly" and lovely data incompatibility will occur).

I also am not entirely sure why `POST` even returns the `Value` module -- is the idea to make sure we only ever return top-level JSON objects (to avoid the various cross-site scripting attacks that can result)? If so, we should probably make `GET` return `Value` too.

**Comment by kennib** [comment]
I think returning the JSON only version is best. But this is a decision I made during tutor training and only partially implements. The docs should be updated to reflect the newer simpler API.

**Comment by cyphar** [comment]
Sure, I can do that -- though I do wonder whether it would be a good idea to block non-`{}` JSON objects? It's not the end of the world (these aren't production applications after all) but it's probably a good idea to get the students into the mindset of "always operate in JSON objects".
